@extends('layouts.app')
@section('title', 'My Classes')
@push('style')
<style>
.classes-card{border:0;border-radius:13px;overflow:hidden}.classes-table{margin-bottom:0;min-width:1150px}.classes-table thead th{background:#4b49ac;border:0;color:#fff;font-size:11px;font-weight:700;letter-spacing:.04em;padding:14px 16px;text-transform:uppercase}.classes-table tbody td{border-color:#edf0f3;padding:16px;vertical-align:middle}.course-code{color:#4b49ac;font-size:11px;font-weight:700}.progress{height:7px;min-width:120px}.detail-cell{background:#f8f9fc!important;padding:20px!important}.schedule-table{background:#fff;margin:0;min-width:900px}.schedule-table th{background:#ececfa!important;color:#4b49ac!important;font-size:11px;padding:11px 13px!important}.schedule-table td{padding:12px 13px!important}.locked-button{cursor:not-allowed}.curriculum-block{border-left:3px solid #4b49ac;margin-bottom:11px;padding-left:12px}.classes-card .pagination{margin-bottom:0}
</style>
@endpush
@section('main')
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4"><div><h3 class="font-weight-bold mb-1">My Classes</h3><p class="text-muted mb-0">Course dan jadwal training yang sudah terdaftar.</p></div><span class="badge badge-primary px-3 py-2">{{ $classes->total() }} class aktif</span></div>
@if(session('error'))<div class="alert alert-danger alert-dismissible fade show">{{ session('error') }}<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button></div>@endif
<div class="card classes-card">
<div class="card-body border-bottom"><form method="GET" action="{{ route('student-classes.index') }}" class="row align-items-end"><div class="col-md-9 form-group mb-md-0"><label for="search">Cari Class</label><input id="search" name="search" value="{{ $search }}" class="form-control" placeholder="Nama atau kode course"></div><div class="col-md-3"><button class="btn btn-primary btn-block"><i class="ti-search mr-1"></i>Cari</button></div></form></div>
@if($classes->isNotEmpty())
<div class="table-responsive"><table class="table classes-table"><thead><tr><th>No.</th><th>Course</th><th>Kategori</th><th>Guru</th><th>Jadwal Pertemuan</th><th>Jadwal Terdekat</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@foreach($classes as $class)
@php
$meetingTotal=$class->course->sections->sum(fn($section)=>$section->lessons->sum('meetings'));$scheduledTotal=$class->paidSchedules->count();$progress=$meetingTotal?min(100,round(($scheduledTotal/$meetingTotal)*100)):0;$nextSchedule=$class->paidSchedules->first(fn($schedule)=>!$schedule->training_date->isBefore(today()));$detailId='class-detail-'.$class->id;
@endphp
<tr><td>{{ $classes->firstItem()+$loop->index }}</td><td><span class="course-code">{{ $class->course->code }}</span><strong class="d-block mt-1">{{ $class->course->name }}</strong><small class="text-muted">TRX-{{ str_pad($class->id,6,'0',STR_PAD_LEFT) }}</small></td><td><span class="badge badge-light">{{ $class->course->category->name }}</span></td><td>@forelse($class->course->teachers as $teacher)<span class="badge badge-info mr-1 mb-1">{{ $teacher->name }}</span>@empty<span class="text-warning">Belum ditentukan</span>@endforelse</td><td><div class="d-flex justify-content-between mb-1"><small>{{ $scheduledTotal }}/{{ $meetingTotal }}</small><small>{{ $progress }}%</small></div><div class="progress"><div class="progress-bar bg-success" style="width:{{ $progress }}%"></div></div></td><td>@if($nextSchedule)<strong class="d-block text-nowrap">{{ $nextSchedule->training_date->translatedFormat('d M Y') }}</strong><small class="text-muted">{{ substr($nextSchedule->start_time,0,5) }}–{{ substr($nextSchedule->end_time,0,5) }} WIB</small>@else<span class="text-muted">Tidak ada jadwal mendatang</span>@endif</td><td>@if($scheduledTotal >= $meetingTotal && $meetingTotal > 0)<span class="badge badge-success">Terjadwal Lengkap</span>@elseif($scheduledTotal > 0)<span class="badge badge-warning">Sebagian Terjadwal</span>@else<span class="badge badge-secondary">Belum Terjadwal</span>@endif</td><td><button type="button" class="btn btn-sm btn-outline-primary" data-toggle="collapse" data-target="#{{ $detailId }}" aria-expanded="false" aria-controls="{{ $detailId }}"><i class="ti-eye mr-1"></i>Lihat Jadwal</button></td></tr>
<tr class="collapse" id="{{ $detailId }}"><td colspan="8" class="detail-cell"><h6 class="font-weight-bold mb-3"><i class="ti-calendar text-primary mr-1"></i>Jadwal Training</h6>
@if($class->paidSchedules->isNotEmpty())<div class="table-responsive"><table class="table table-bordered schedule-table"><thead><tr><th>Tanggal</th><th>Pertemuan & Materi</th><th>Guru</th><th>Jam</th><th>Catatan</th><th>Zoom</th></tr></thead><tbody>@foreach($class->paidSchedules as $schedule)<tr><td><strong class="text-nowrap">{{ $schedule->training_date->translatedFormat('d M Y') }}</strong><small class="text-muted d-block">{{ $schedule->training_date->translatedFormat('l') }}</small></td><td><small class="text-primary d-block">{{ $schedule->lesson?->section?->name ?? 'Materi' }} · Pertemuan {{ $schedule->meeting_number ?? '-' }}</small><strong>{{ $schedule->lesson?->title ?? $class->course->name }}</strong></td><td>{{ $schedule->teacher->name }}</td><td class="text-nowrap">{{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }} WIB</td><td>{{ $schedule->notes ?: '—' }}</td><td class="text-nowrap">@if($schedule->canJoinZoom())<a href="{{ route('student-classes.join',$schedule) }}" target="_blank" rel="noopener noreferrer" class="btn btn-sm btn-primary"><i class="ti-video-camera mr-1"></i>Masuk Zoom</a>@elseif($schedule->hasEnded())<button class="btn btn-sm btn-secondary locked-button" disabled><i class="ti-check mr-1"></i>Jadwal Selesai</button>@elseif($schedule->zoom_url)<button class="btn btn-sm btn-secondary locked-button" disabled><i class="ti-lock mr-1"></i>Belum Aktif</button>@else<span class="text-warning">Zoom belum tersedia</span>@endif</td></tr>@endforeach</tbody></table></div>@else<div class="alert alert-info">Admin belum membuat jadwal training untuk class ini.</div>@endif
<h6 class="font-weight-bold mt-4 mb-3"><i class="ti-list text-primary mr-1"></i>Kurikulum</h6><div class="row">@forelse($class->course->sections as $section)<div class="col-md-6"><div class="curriculum-block"><strong>{{ $loop->iteration }}. {{ $section->name }}</strong>@forelse($section->lessons as $lesson)<small class="text-muted d-flex justify-content-between mt-2"><span>{{ $lesson->title }}</span><span>{{ $lesson->meetings }} pertemuan</span></small>@empty<small class="text-muted d-block mt-2">Belum ada materi.</small>@endforelse</div></div>@empty<div class="col-12 text-muted">Kurikulum belum tersedia.</div>@endforelse</div></td></tr>
@endforeach
</tbody></table></div><div class="card-footer bg-white d-flex flex-wrap justify-content-between align-items-center"><small class="text-muted">Menampilkan {{ $classes->firstItem() }}–{{ $classes->lastItem() }} dari {{ $classes->total() }} class</small>@if($classes->hasPages()){{ $classes->links('pagination::bootstrap-4') }}@endif</div>
@else<div class="card-body text-center py-5"><i class="ti-book h2 text-muted"></i><h5 class="mt-3">Belum ada class</h5><p class="text-muted">Class akan muncul setelah pembayaran course diverifikasi oleh admin.</p><a href="{{ route('student-courses.index') }}" class="btn btn-primary">Lihat Semua Course</a></div>@endif
</div>
@endsection
