@extends('layouts.app')

@section('title', 'Gaji Guru')

@push('style')
<style>
    .pay-stat,.pay-card{border:0;border-radius:13px}.pay-icon{align-items:center;border-radius:10px;display:flex;font-size:20px;height:46px;justify-content:center;width:46px}.pay-table{margin-bottom:0;min-width:1000px}.pay-table thead th{background:#f5f6fa;border:0;color:#6c757d;font-size:11px;font-weight:700;letter-spacing:.04em;padding:14px 16px;text-transform:uppercase}.pay-table tbody td{border-color:#edf0f3;padding:15px 16px;vertical-align:middle}.money{color:#4b49ac;font-weight:700;white-space:nowrap}.pay-code{color:#4b49ac;font-size:11px;font-weight:700}.pay-card .pagination{margin-bottom:0}
</style>
@endpush

@section('main')
<div class="mb-4"><h3 class="font-weight-bold mb-1">Gaji Guru</h3><p class="text-muted mb-0">Bayar akumulasi honor pertemuan guru yang telah menyelesaikan report pembelajaran.</p></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show">{{ session('success') }}<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button></div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="row mb-4"><div class="col-md-4 mb-3"><div class="card pay-stat h-100"><div class="card-body d-flex align-items-center"><span class="pay-icon bg-warning text-white mr-3"><i class="ti-wallet"></i></span><div><small class="text-muted">Total Belum Dibayar</small><h4 class="font-weight-bold mb-0">Rp {{ number_format($totalUnpaid,0,',','.') }}</h4></div></div></div></div><div class="col-md-4 mb-3"><div class="card pay-stat h-100"><div class="card-body d-flex align-items-center"><span class="pay-icon bg-success text-white mr-3"><i class="ti-check"></i></span><div><small class="text-muted">Total Sudah Dibayar</small><h4 class="font-weight-bold mb-0">Rp {{ number_format($totalPaid,0,',','.') }}</h4></div></div></div></div><div class="col-md-4 mb-3"><div class="card pay-stat h-100"><div class="card-body d-flex align-items-center"><span class="pay-icon bg-primary text-white mr-3"><i class="ti-user"></i></span><div><small class="text-muted">Guru Menunggu Pembayaran</small><h4 class="font-weight-bold mb-0">{{ $unpaidTeachers }} guru</h4></div></div></div></div></div>

<div class="card pay-card mb-4"><div class="card-body border-bottom"><div class="d-flex flex-wrap justify-content-between align-items-center"><div><h5 class="font-weight-bold mb-1">Saldo Gaji Guru</h5><small class="text-muted">Pembayaran mencakup seluruh salary yang belum dibayar.</small></div><form method="GET" action="{{ route('admin-teacher-salaries.index') }}" class="form-inline mt-2 mt-md-0"><input name="search" value="{{ $search }}" class="form-control mr-2" placeholder="Nama atau email guru"><button class="btn btn-primary"><i class="ti-search"></i></button></form></div></div>
    <div class="table-responsive"><table class="table pay-table"><thead><tr><th>Guru</th><th>Rekening Tujuan</th><th>Pertemuan Belum Dibayar</th><th>Total Gaji</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($teachers as $teacher)<tr><td><strong class="d-block">{{ $teacher->name }}</strong><small class="text-muted">{{ $teacher->email }}</small></td><td>@if($teacher->bank_account_number)<strong class="d-block">{{ $teacher->bank_name }}</strong><small class="text-muted">{{ $teacher->bank_account_number }} · {{ $teacher->bank_account_holder }}</small>@else<span class="text-danger">Data rekening belum lengkap</span>@endif</td><td>{{ $teacher->unpaid_meetings_count }} pertemuan</td><td><span class="money">Rp {{ number_format($teacher->unpaid_salary_total ?? 0,0,',','.') }}</span></td><td>@if(($teacher->unpaid_meetings_count ?? 0)>0)<span class="badge badge-warning">Menunggu Pembayaran</span>@else<span class="badge badge-light">Tidak Ada Tagihan</span>@endif</td><td>@if(($teacher->unpaid_meetings_count ?? 0)>0)<a href="{{ route('admin-teacher-salaries.create',$teacher) }}" class="btn btn-sm btn-primary"><i class="ti-wallet mr-1"></i>Bayar Gaji</a>@else<span class="text-muted">—</span>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">Belum ada data guru.</td></tr>@endforelse</tbody></table></div>
    @if($teachers->hasPages())<div class="card-footer bg-white">{{ $teachers->links('pagination::bootstrap-4') }}</div>@endif
</div>

<div class="card pay-card"><div class="card-body border-bottom"><h5 class="font-weight-bold mb-1">Riwayat Pembayaran Gaji</h5><small class="text-muted">Daftar transfer gaji yang telah dilakukan admin.</small></div><div class="table-responsive"><table class="table pay-table"><thead><tr><th>ID Pembayaran</th><th>Guru</th><th>Tanggal Transfer</th><th>Rekening Tujuan</th><th>Nominal</th><th>Dibayar Oleh</th><th>Bukti</th></tr></thead><tbody>@forelse($payouts as $payout)<tr><td><span class="pay-code">PAY-{{ str_pad($payout->id,6,'0',STR_PAD_LEFT) }}</span></td><td><strong>{{ $payout->teacher->name }}</strong></td><td>{{ $payout->transfer_date->translatedFormat('d M Y') }}</td><td><strong class="d-block">{{ $payout->bank_name }}</strong><small class="text-muted">{{ $payout->bank_account_number }} · {{ $payout->bank_account_holder }}</small></td><td><span class="money">Rp {{ number_format($payout->amount,0,',','.') }}</span></td><td>{{ $payout->payer?->name ?? 'Admin' }}</td><td><a href="{{ route('admin-teacher-salaries.proof',$payout) }}" target="_blank" class="btn btn-sm btn-outline-primary"><i class="ti-receipt mr-1"></i>Lihat Bukti</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">Belum ada pembayaran gaji.</td></tr>@endforelse</tbody></table></div>@if($payouts->hasPages())<div class="card-footer bg-white">{{ $payouts->links('pagination::bootstrap-4') }}</div>@endif</div>
@endsection
